steps:
  - label: ":percy::hamster: test"
    commands:
      - "make build-test"
      - "make test"
    timeout_in_minutes: 20
    env:
      EMBER_TEST_BUILD: 'true'

  - label: ":percy::hamster: publish"
    branches: "master"
    commands:
      - "make publish"
    timeout_in_minutes: 20

  - wait

  - label: "deploy :rocket::percy::rocket:"
    trigger: "deploy-web"
    branches: "master"
    async: true
    build:
      message: "${BUILDKITE_MESSAGE}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        TAG: "${BUILDKITE_COMMIT}"
